name: Go

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-and-push.yml'
      - 'server/**'
      - 'Dockerfile'
      - 'azure/**
      '
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      # - name: golangci-lint
      #   uses: golangci/golangci-lint-action@v3
      #   with:
      #     # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
      #     version: v1.29
      #     working-directory: server

      - name: Build
        run: GOOS=linux go build -v ./server/hello.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: stevengonsalvez/docker-knife:latest
